fetch("https://www.apicountries.com/countries")
.then(a=>{
    return a.json()
}).then(b=>{
    console.log(b[0])
    console.log("The name of the country is "+(b[0].name))
    console.log("The top level domain of the country is "+(b[0].topLevelDomain))
    console.log("The alpha 2 code of the country is "+(b[0].alpha2Code))
    console.log("The alpha 3 code of the country is "+(b[0].alpha3Code))
    console.log("The calling codes of the country is "+(b[0].callingCodes))
    console.log("The capital of the country is "+(b[0].capital))
    console.log("The alt spellings of the country is "+(b[0].altSpellings))
    console.log("The sub region of the country is "+(b[0].subregion))
    console.log("The region of the country is "+(b[0].region))
    console.log("The population of the country is "+(b[0].population))
    console.log("The latitude of the country is "+(b[0].latlng[0])+" and the longitude of the country is "+(b[0].latlng[1]))
    console.log("The demonym of the country is "+(b[0].demonym))
    console.log("The area of the country is "+(b[0].area))
    console.log("The time zone of the country is "+(b[0].timezones))
    console.log("The borders of the country is "+(b[0].borders).join(" and "))
    console.log("The native name: of the country is "+(b[0].nativeName))
    console.log("The numeric code of the country is "+(b[0].numericCode))
})