fetch("https://www.apicountries.com/countries")
.then(a=>{
    return a.json()
}).then(b=>{
    console.log(b[0])
    console.log("The name of the country is "+(b[0].name))
    console.log("The top level domain of the country is "+(b[0].topLevelDomain))
    console.log("The alpha 2 code of the country is "+(b[0].alpha2Code))
    console.log("The alpha 3 code of the country is "+(b[0].alpha3Code))
    console.log("The calling codes of the country is "+(b[0].callingCodes))
    console.log("The capital of the country is "+(b[0].capital))
    console.log("The alt spellings of the country is "+(b[0].altSpellings))
    console.log("The sub region of the country is "+(b[0].subregion))
    console.log("The region of the country is "+(b[0].region))
    console.log("The population of the country is "+(b[0].population))
    console.log("The latitude of the country is "+(b[0].latlng[0])+" and the longitude of the country is "+(b[0].latlng[1]))
    console.log("The demonym of the country is "+(b[0].demonym))
    console.log("The area of the country is "+(b[0].area))
    console.log("The time zone of the country is "+(b[0].timezones))
    console.log("The borders of the country is "+(b[0].borders).join(" and "))
    console.log("The native name: of the country is "+(b[0].nativeName))
    console.log("The numeric code of the country is "+(b[0].numericCode))
    console.log("The currency code of the country is "+(b[0].currencies[0].code))
    console.log("The currency name of the country is "+(b[0].currencies[0].name))
    console.log("The currency symbol of the country is "+(b[0].currencies[0].symbol))
    console.log("The 1st iso639_1 of the country is "+(b[0].languages[0].iso639_1))
    console.log("The 1st iso639_2 of the country is "+(b[0].languages[0].iso639_2))
    console.log("The 1st language spoken of the country is "+(b[0].languages[0].name))
    console.log("The 1st native name of the country is "+(b[0].languages[0].nativeName))
    console.log("The 2nd iso639_1 of the country is "+(b[0].languages[1].iso639_1))
    console.log("The 2nd iso639_2 of the country is "+(b[0].languages[1].iso639_2))
    console.log("The 2nd language spoken of the country is "+(b[0].languages[1].name))
    console.log("The 2nd native name of the country is "+(b[0].languages[1].nativeName))
    console.log("The 3rd iso639_1 of the country is "+(b[0].languages[2].iso639_1))
    console.log("The 3rd iso639_2 of the country is "+(b[0].languages[2].iso639_2))
    console.log("The 3rd language spoken of the country is "+(b[0].languages[2].name))
    console.log("The 3rd native name of the country is "+(b[0].languages[2].nativeName))

    console.log("The br translation of the country is "+(b[0].translations.br))
    console.log("The pt translation of the country is "+(b[0].translations.pt))
    console.log("The nl translation of the country is "+(b[0].translations.nl))
    console.log("The hr translation of the country is "+(b[0].translations.hr))
    console.log("The fa translation of the country is "+(b[0].translations.fa))
    console.log("The de translation of the country is "+(b[0].translations.de))
    console.log("The es translation of the country is "+(b[0].translations.es))
    console.log("The fr translation of the country is "+(b[0].translations.fr))
    console.log("The ja translation of the country is "+(b[0].translations.ja))
    console.log("The it translation of the country is "+(b[0].translations.it))
    console.log("The hu translation of the country is "+(b[0].translations.hu))
    console.log("The regional blocs acronym of the country is "+(b[0].regionalBlocs[0].acronym))
    console.log("The regional blocs name of the country is "+(b[0].regionalBlocs[0].name))
    console.log("The cioc of the country is "+(b[0].cioc))
})